dry_run: false

github:
  organization: "UChi-CI"
  leaderboard_repo: "data-37712-win25-leaderboard"
  assignment_prefix: "data-37712-win25-assignment-1-"
  assignment_name: "assignment-1"

test_data:
  directory: "held-out-test-data"
  assignment_test_data: "a1-test-data"

utils_module: "assignment_1_utils"

staff:
  # - toddnief
  # - ari-holtzman

results_files:
  - mlp_newsgroups_test_predictions.csv
  - mlp_sst2_test_predictions.csv
  - perceptron_newsgroups_test_predictions.csv
  - perceptron_sst2_test_predictions.csv